name: BetterEssentialsV2
version: 1.0
main: me.markiscool.betteressentialsv2.BetterEssentialsV2Plugin
api-version: 1.13
author: MarkIsCool
depend: [UsersAPI]
description: Better version of essentials (low key)
commands:
  clearinventory:
    aliases: [ci, clear]
    description: Clears inventory of yourself, or another
    usage: /<command> [player]
  give:
    aliases: [item, i]
    description: Gives you item
    usage: /<command> [player] <item> <amount>
  warp:
    description: Warp to an area
    usage: /<command> <warp_name>
  setwarp:
    description: Set your location as a new warp
    usage: /<command> <warp_name>
  deletewarp:
    aliases: [delwarp]
    description: Deletes a warp
    usage: /<command> <warp_name>
  warps:
    description: View all the warps you can warp to
    usage: /<command>
  fly:
    description: Gives you, or another user, fly.
    usage: /<command> [player]
  heal:
    description: Heal you, or another player.
    usage: /<command> [player]
  feed:
    description: Feed you, or another player.
    usage: /<command> [player]
  vanish:
    description: Hides you, or another player, from another players
    usage: /<command> [player]
    aliases: [v]
  speed:
    description: Sets your, or another player's, walk & fly speed.
    usage: /<command> [player] <1-10>
  seen:
    description: Checks when the last time a player has been online.
    usage: /<command> <player>
  gamemode:
    description: Set your gamemode
    usage: /<command> <mode> [player]
    aliases: [gm]
  gamemodesurvival:
    description: Survival game-mode shortcut
    usage: /<command> [player]
    aliases: [gms, gamemodes, gmsu, gamemodesurv]
  gamemodecreative:
    description: Creative game-mode shortcut
    usage: /<command> [player]
    aliases: [gmc, gamemodec]
  gamemodeadventure:
    description: Adventure game-mode shortcut
    usage: /<command> [player]
    aliases: [gma, gamemodea]
  gamemodespectator:
    description: Spectator game-mode shortcut
    usage: /<command> [player]
    aliases: [gmsp, gmspec, gamemodespec]
  spawn:
    description: Teleports you to spawn
    usage: /<command> [player]
  setspawn:
    description: Sets your location as spawn
    usage: /<command>
  balance:
    description: Check your, or another player's, balance.
    usage: /<command> [player]
    aliases: [bal]
  balancetop:
    description: Check who has the most balance on the server.
    usage: /<command>
    aliases: [baltop]
  economy:
    description: Base economy command.
    usage: /<command> <set/reset/add/remove> <player> <amount>
    aliases: [eco]
  kill:
    description: Kill command
    usage: /<command> [player]
  ban:
    description: Ban command.
    usage: /<command> <reason> [reason]
  unban:
    description: Unban a banned player
    usage: /<command> <player>
  kick:
    description: Kick a player
    usage: /<command> <player>
  tempban:
    description: Temporarily ban a player
    usage: /<command> <player> <duration_seconds>